/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.pr.senac.ads.nbb.view;

import br.pr.senac.ads.nbb.dao.GenericDAO;
import br.pr.senac.ads.nbb.controller.AtletaController;
import br.pr.senac.ads.nbb.dao.AtletaDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import br.pr.senac.ads.nbb.model.Atleta;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gustavo.8965
 */
public class CadastroAtletaPesquisar extends javax.swing.JDialog {

    /**
     * Creates new form CadastroAtletaPesquisar
     */
    public CadastroAtletaPesquisar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jTextFieldNome.setEditable(false);
        jTextFieldAltura.setEditable(false);
        jTextFieldDataNascimento.setEditable(false);
        jTextFieldPeso.setEditable(false);
        jTextFieldTime.setEditable(false);
        jTextFieldPosicaoTime.setEditable(false);
        jTextFieldEnvergadura.setEditable(false);
        jTextFieldClassificacaoNBB.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNomePesquisar = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldAltura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDataNascimento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPosicaoTime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEnvergadura = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldClassificacaoNBB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBanco = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Atleta");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)), "Pesquisar Atleta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nome:");

        jTextFieldCodigo.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Código: (Não Mexer)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldCodigo))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jButtonPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setMaximumSize(new java.awt.Dimension(94, 27));
        jButtonLimpar.setMinimumSize(new java.awt.Dimension(94, 27));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setMaximumSize(new java.awt.Dimension(94, 27));
        jButtonExcluir.setMinimumSize(new java.awt.Dimension(94, 27));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setMaximumSize(new java.awt.Dimension(94, 27));
        jButtonAlterar.setMinimumSize(new java.awt.Dimension(94, 27));
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonFechar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.setMaximumSize(new java.awt.Dimension(94, 27));
        jButtonFechar.setMinimumSize(new java.awt.Dimension(94, 27));
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setMaximumSize(new java.awt.Dimension(94, 27));
        jButtonSalvar.setMinimumSize(new java.awt.Dimension(94, 27));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nome:");

        jTextFieldNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNome.setEnabled(false);

        jTextFieldAltura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldAltura.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Altura:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Data de Nascimento");

        jTextFieldDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldDataNascimento.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Peso");

        jTextFieldPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPeso.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Time");

        jTextFieldTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTime.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Posição no Time:");

        jTextFieldPosicaoTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPosicaoTime.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Envergadura:");

        jTextFieldEnvergadura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldEnvergadura.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Classificação NBB:");

        jTextFieldClassificacaoNBB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldClassificacaoNBB.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNome)
                    .addComponent(jTextFieldAltura)
                    .addComponent(jTextFieldDataNascimento)
                    .addComponent(jTextFieldPeso)
                    .addComponent(jTextFieldTime)
                    .addComponent(jTextFieldPosicaoTime)
                    .addComponent(jTextFieldEnvergadura)
                    .addComponent(jTextFieldClassificacaoNBB)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPosicaoTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEnvergadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClassificacaoNBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTableBanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jTableBanco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Altura", "Data de Nascimento", "Peso", "Time de Basquete", "Posição no Time", "Envergadura", "Classificação na NBB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableBancoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBanco);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limparCampos() {
        // Bloqueando Botões e Campos de Inserção:
        jButtonSalvar.setEnabled(false);
        
        jTextFieldNome.setEditable(false);
        jTextFieldAltura.setEditable(false);
        jTextFieldDataNascimento.setEditable(false);
        jTextFieldPeso.setEditable(false);
        jTextFieldTime.setEditable(false);
        jTextFieldPosicaoTime.setEditable(false);
        jTextFieldEnvergadura.setEditable(false);
        jTextFieldClassificacaoNBB.setEditable(false);
        
        
        jTextFieldNome.setEnabled(false);
        jTextFieldAltura.setEnabled(false);
        jTextFieldDataNascimento.setEnabled(false);
        jTextFieldPeso.setEnabled(false);
        jTextFieldTime.setEnabled(false);
        jTextFieldPosicaoTime.setEnabled(false);
        jTextFieldEnvergadura.setEnabled(false);
        jTextFieldClassificacaoNBB.setEnabled(false);
        
        //Limpando os campos:
        jTextFieldNomePesquisar.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldNome.setText("");
        jTextFieldAltura.setText("");
        jTextFieldDataNascimento.setText("");
        jTextFieldPeso.setText("");
        jTextFieldTime.setText("");
        jTextFieldPosicaoTime.setText("");
        jTextFieldEnvergadura.setText("");
        jTextFieldClassificacaoNBB.setText("");
    }
    
    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        dispose();
        HomePage dialog = new HomePage(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        jButtonSalvar.setEnabled(true);
        
        jTextFieldNome.setEnabled(true);
        jTextFieldAltura.setEnabled(true);
        jTextFieldDataNascimento.setEnabled(true);
        jTextFieldPeso.setEnabled(true);
        jTextFieldTime.setEnabled(true);
        jTextFieldPosicaoTime.setEnabled(true);
        jTextFieldEnvergadura.setEnabled(true);
        jTextFieldClassificacaoNBB.setEnabled(true);
        
        jTextFieldNome.setEditable(true);
        jTextFieldAltura.setEditable(true);
        jTextFieldDataNascimento.setEditable(true);
        jTextFieldPeso.setEditable(true);
        jTextFieldTime.setEditable(true);
        jTextFieldPosicaoTime.setEditable(true);
        jTextFieldEnvergadura.setEditable(true);
        jTextFieldClassificacaoNBB.setEditable(true);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        
        String nome = jTextFieldNomePesquisar.getText();
        
        if(nome == "" || nome.equals("")) {
            listarCampos();
        } else {
            listarPesquisa(nome);
        }
            
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTableBancoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBancoMousePressed
        try {
            carregarCampos();
        } catch (ParseException ex) {
            Logger.getLogger(CadastroAtletaPesquisar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableBancoMousePressed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        AtletaController atletaController = new AtletaController();
        
        atletaController.setCodigo(jTextFieldCodigo.getText());
        atletaController.setNome(jTextFieldNome.getText());
        atletaController.setAltura(jTextFieldAltura.getText());
        atletaController.setDataNascimento(jTextFieldDataNascimento.getText());
        atletaController.setPeso(jTextFieldPeso.getText());
        atletaController.setTime(jTextFieldTime.getText());
        atletaController.setPosicaoTime(jTextFieldPosicaoTime.getText());
        atletaController.setEnvergadura(jTextFieldEnvergadura.getText());
        atletaController.setClassificacaoNBB(jTextFieldClassificacaoNBB.getText());
        
        try {
            atletaController.atualizar(
                    atletaController.getCodigo(),
                    atletaController.getNome(),
                    atletaController.getAltura(),
                    atletaController.getDataNascimento(),
                    atletaController.getPeso(),
                    atletaController.getTime(),
                    atletaController.getPosicaoTime(),
                    atletaController.getEnvergadura(),
                    atletaController.getClassificacaoNBB());
                    JOptionPane.showMessageDialog(this, "Atleta atualizado com sucesso!");
                    listarCampos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Não foi possível salvar atleta!" + e.getLocalizedMessage());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Data possui formato inválido!" + e.getLocalizedMessage());
        }
        
        bloquearCampos();
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    
    private void bloquearCampos() {
        
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jTextFieldNome.setEditable(false);
        jTextFieldAltura.setEditable(false);
        jTextFieldDataNascimento.setEditable(false);
        jTextFieldPeso.setEditable(false);
        jTextFieldTime.setEditable(false);
        jTextFieldPosicaoTime.setEditable(false);
        jTextFieldEnvergadura.setEditable(false);
        jTextFieldClassificacaoNBB.setEditable(false);
        
    }
    
    
    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        AtletaController atletaController = new AtletaController();
        
        atletaController.setCodigo(jTextFieldCodigo.getText());
        atletaController.setNome(jTextFieldNome.getText());
        atletaController.setAltura(jTextFieldAltura.getText());
        atletaController.setDataNascimento(jTextFieldDataNascimento.getText());
        atletaController.setPeso(jTextFieldPeso.getText());
        atletaController.setTime(jTextFieldTime.getText());
        atletaController.setPosicaoTime(jTextFieldPosicaoTime.getText());
        atletaController.setEnvergadura(jTextFieldEnvergadura.getText());
        atletaController.setClassificacaoNBB(jTextFieldClassificacaoNBB.getText());
        
        try {
            atletaController.deletar(
                    atletaController.getCodigo(),
                    atletaController.getNome(),
                    atletaController.getAltura(),
                    atletaController.getDataNascimento(),
                    atletaController.getPeso(),
                    atletaController.getTime(),
                    atletaController.getPosicaoTime(),
                    atletaController.getEnvergadura(),
                    atletaController.getClassificacaoNBB());
                    JOptionPane.showMessageDialog(this, "Atleta deletado com sucesso!");
                    listarCampos();
                    limparCampos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Não foi possível salvar atleta!" + e.getLocalizedMessage());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Data possui formato inválido!" + e.getLocalizedMessage());
        }
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    
    // Método que vai listar todos os campos do banco de dados caso a pessoa não insira nada na hora de pesquisar
    private void listarCampos() {
        
        try {
            
            AtletaDAO objAtleta = new AtletaDAO();
            DefaultTableModel model = (DefaultTableModel) jTableBanco.getModel();
            model.setRowCount(0);
            
            ArrayList<Atleta> lista = objAtleta.listarTodos();
            
            for(int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[]{
                    lista.get(i).getCodigo(),
                    lista.get(i).getNome(),
                    lista.get(i).getAltura(),
                    lista.get(i).getDataNascimento(),
                    lista.get(i).getPeso(),
                    lista.get(i).getTime(),
                    lista.get(i).getPosicaoTime(),
                    lista.get(i).getEnvergadura(),
                    lista.get(i).getClassificacaoNBB()
                });
            }
                    
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro no ListarCampos");
        }
        
    }
    
    // Método que vai retornar uma pesquisa com base no nome selecionado.
    private void listarPesquisa(String nome) {
        
        try {
            
            AtletaDAO objAtleta = new AtletaDAO();
            DefaultTableModel model = (DefaultTableModel) jTableBanco.getModel();
            model.setRowCount(0);
            
            ArrayList<Atleta> lista = objAtleta.listarPesquisaNome(nome);
            
            for(int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[]{
                    lista.get(i).getCodigo(),
                    lista.get(i).getNome(),
                    lista.get(i).getAltura(),
                    lista.get(i).getDataNascimento(),
                    lista.get(i).getPeso(),
                    lista.get(i).getTime(),
                    lista.get(i).getPosicaoTime(),
                    lista.get(i).getEnvergadura(),
                    lista.get(i).getClassificacaoNBB()
                });
            }
                    
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro no ListarCampos");
        }
        
    }
    
    //Método que vai carregar as informações que trouxemos do banco de dados e setar no lado esquerdo aonde contém os TextFields
    private void carregarCampos() throws ParseException {
        DateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        dt.setLenient(false);
        
        int linha = jTableBanco.getSelectedRow();
        
        jTextFieldCodigo.setText(jTableBanco.getModel().getValueAt(linha, 0).toString());
        jTextFieldNome.setText(jTableBanco.getModel().getValueAt(linha, 1).toString());
        jTextFieldAltura.setText(jTableBanco.getModel().getValueAt(linha, 2).toString());
//        jTextFieldDataNascimento.setText(jTableBanco.getModel().getValueAt(linha, 3).toString());
        jTextFieldPeso.setText(jTableBanco.getModel().getValueAt(linha, 4).toString());
        jTextFieldTime.setText(jTableBanco.getModel().getValueAt(linha, 5).toString());
        jTextFieldPosicaoTime.setText(jTableBanco.getModel().getValueAt(linha, 6).toString());
        jTextFieldEnvergadura.setText(jTableBanco.getModel().getValueAt(linha, 7).toString());
        jTextFieldClassificacaoNBB.setText(jTableBanco.getModel().getValueAt(linha, 8).toString());

        //Formatando minha data
        String minhaData = dt.format((jTableBanco.getModel().getValueAt(linha, 3)));
        jTextFieldDataNascimento.setText(minhaData);
        
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBanco;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldClassificacaoNBB;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDataNascimento;
    private javax.swing.JTextField jTextFieldEnvergadura;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomePesquisar;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldPosicaoTime;
    private javax.swing.JTextField jTextFieldTime;
    // End of variables declaration//GEN-END:variables
}
